languageCode: en-us
title: pkmnsandy
theme: hugo-lithium
googleAnalytics: UA-171571381-1
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /blog/:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Publications
      url: /publications/
      weight: 4
    - name: Blog
      url: /blog
      weight: 5
    - name: CV
      url: https://1drv.ms/b/s!AsD1AfPqmMeCg4UdTw8trq-9t4sajQ
      weight: 6
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: This is my personal website. Welcome.
  favicon: favicon.png
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: logo
    name: Sandy Jan Labarosa
    height: 50
    url: logo.png
    width: 150
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
